import Sidebar from './components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const session = false

  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <div className="m-auto max-w-6xl mt-12">
          <div className="fixed w-60">{session && <Sidebar />}</div>
          <div className="ml-64">{children}</div>
        </div>
      </body>
    </html>
  )
}
